### ISSUE TITLE
dwarf-0.3.0 fails to compile with GCC-5 on OS X

### ISSUE THREAD

**Issue by DomT4** [elboza/dwarf-ng#1]
```
==> make install
Making install in src
Making install in libdwarf
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-y.tab.o `test -f 'y.tab.c' || echo './'`y.tab.c
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-lex.cfgyy.o `test -f 'lex.cfgyy.c' || echo './'`lex.cfgyy.c
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-vars.o `test -f 'vars.c' || echo './'`vars.c
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-utils.o `test -f 'utils.c' || echo './'`utils.c
In file included from lex.cfgyy.c:61:0:
/usr/include/inttypes.h:235:8: error: unknown type name 'intmax_t'
 extern intmax_t
        ^
/usr/include/inttypes.h:236:9: error: unknown type name 'intmax_t'
 imaxabs(intmax_t j);
         ^
/usr/include/inttypes.h:240:2: error: unknown type name 'intmax_t'
  intmax_t quot;
  ^
/usr/include/inttypes.h:241:2: error: unknown type name 'intmax_t'
  intmax_t rem;
  ^
/usr/include/inttypes.h:246:9: error: unknown type name 'intmax_t'
 imaxdiv(intmax_t __numer, intmax_t __denom);
         ^
/usr/include/inttypes.h:246:27: error: unknown type name 'intmax_t'
 imaxdiv(intmax_t __numer, intmax_t __denom);
                           ^
/usr/include/inttypes.h:250:8: error: unknown type name 'intmax_t'
 extern intmax_t
        ^
/usr/include/inttypes.h:256:8: error: unknown type name 'uintmax_t'
 extern uintmax_t
        ^
/usr/include/inttypes.h:263:8: error: unknown type name 'intmax_t'
 extern intmax_t
        ^
/usr/include/inttypes.h:269:8: error: unknown type name 'uintmax_t'
 extern uintmax_t
        ^
make[3]: *** [libdwarf_a-lex.cfgyy.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

Seems to work fine with GCC-4.9, but the latest GCC 5.2.0 dies during `make install` per the above. Confirmed on OS X 10.9 => 10.11, so seems to be a latest GCC error rather than necessarily platform specific. Passing the `--no-as-needed` flag produced the same failure.

Couldn't test the 0.3.1 release of Dwarf because of this error:

```
==> make install
Making install in src
Making install in libdwarf
bison -y -y -d -v -p cfgyy cfglang.y -o y.tab.c
flex -P cfgyy cfglang.l
make[2]: *** No rule to make target `y.tab.h', needed by `install'.  Stop.
make[2]: *** Waiting for unfinished jobs....
conflicts: 2 reduce/reduce
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

**Comment by elboza** [comment]
solved with dwarf-0.3.2
